version: '3'

networks:
  redis-cluster-net:
    driver: bridge

services:
  # --- Nodes 1-3 (Master) ---
  redis-node-1:
    image: redis:alpine
    container_name: redis-node-1
    # Perintah ini MEMAKSA Redis menyala dalam mode Cluster
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:6379"
    networks:
      - redis-cluster-net

  redis-node-2:
    image: redis:alpine
    container_name: redis-node-2
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:6379"
    networks:
      - redis-cluster-net

  redis-node-3:
    image: redis:alpine
    container_name: redis-node-3
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:6379"
    networks:
      - redis-cluster-net

  # --- Nodes 4-6 (Replica) ---
  redis-node-4:
    image: redis:alpine
    container_name: redis-node-4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:6379"
    networks:
      - redis-cluster-net

  redis-node-5:
    image: redis:alpine
    container_name: redis-node-5
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:6379"
    networks:
      - redis-cluster-net

  redis-node-6:
    image: redis:alpine
    container_name: redis-node-6
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7006:6379"
    networks:
      - redis-cluster-net