version: '3.8'

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:

  # -----------------------------
  # MASTER
  # -----------------------------
  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      redisnet:
        ipv4_address: 172.25.0.10

  # -----------------------------
  # REPLICAS
  # -----------------------------
  redis-replica-1:
    image: bitnami/redis:latest
    container_name: redis-replica-1
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=172.25.0.10
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      redisnet:
        ipv4_address: 172.25.0.11

  redis-replica-2:
    image: bitnami/redis:latest
    container_name: redis-replica-2
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=172.25.0.10
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    networks:
      redisnet:
        ipv4_address: 172.25.0.12

  # (LANJUTKAN UNTUK REPLICA 3â€“10)
  # Gunakan IP:
  # 172.25.0.13
  # 172.25.0.14
  # 172.25.0.15
  # ...
  # 172.25.0.20

  # -----------------------------
  # SENTINELS
  # -----------------------------
  redis-sentinel-1:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-1
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=172.25.0.10
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
    networks:
      redisnet:
        ipv4_address: 172.25.0.30

  redis-sentinel-2:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-2
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=172.25.0.10
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26380:26379"
    networks:
      redisnet:
        ipv4_address: 172.25.0.31

  redis-sentinel-3:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-3
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=172.25.0.10
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26381:26379"
    networks:
      redisnet:
        ipv4_address: 172.25.0.32
