version: '3'
services:
  # Node 1: Master
  redis-master:
    image: redis:alpine
    container_name: redis-master
    ports:
      - "6379:6379"

  # Node 2: Replica 1
  redis-replica-1:
    image: redis:alpine
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master

  # Node 3: Replica 2
  redis-replica-2:
    image: redis:alpine
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master